package com.dshatz.exposed_crud

import kotlin.reflect.KClass
import java.util.UUID

/**
 * Marks the property as an optionally auto-incrementing primary key.
 *
 * To make a composite primary key, annotate multiple columns with this.
 * 
 * @param autoGenerate Whether the ID should be auto-generated by the database
 * @param generator Custom ID generator class. Use Nothing::class (default) to indicate no generator.
 */
@Target(AnnotationTarget.PROPERTY)
annotation class Id(
    val autoGenerate: Boolean = false,
    val generator: KClass<out IdGenerator<*>> = Nothing::class
) {
    companion object {
        /**
         * Empty UUID constant (00000000-0000-0000-0000-000000000000).
         * Used to check if a UUID is empty/not set.
         */
        val UUID_EMPTY: UUID = UUID(0L, 0L)
    }
}
