package com.dshatz.exposed_crud

import kotlin.reflect.KClass

/**
 * Marks the property as an optionally auto-incrementing primary key.
 *
 * To make a composite primary key, annotate multiple columns with this.
 * 
 * @param autoGenerate Whether the ID should be auto-generated by the database
 * @param generator Custom ID generator class. Use Nothing::class (default) to indicate no generator.
 */
@Target(AnnotationTarget.PROPERTY)
annotation class Id(
    val autoGenerate: Boolean = false,
    val generator: KClass<out IdGenerator<*>> = Nothing::class
)
