package com.dshatz.exposed_crud

import com.dshatz.exposed_crud.models.GameTable
import com.dshatz.exposed_crud.helper.TestHelper
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.jetbrains.exposed.v1.jdbc.transactions.transaction
import java.util.*
import kotlin.test.BeforeTest
import kotlin.test.Test

class IndexTest {

    private lateinit var db: Database

    @BeforeTest
    fun init() {
        db = TestHelper.prepareDatabase(
            listOf(GameTable),
            url = "jdbc:h2:mem:index_test_${UUID.randomUUID()};DB_CLOSE_DELAY=-1;MODE=LEGACY"
        )
        
        transaction(db) {
            println("Created tables:")
            SchemaUtils.listTables().forEach { println("  - $it") }
        }
    }

    @Test
    fun `table should be created with indexes`() {
        transaction(db) {
            // Verify table exists
            val tables = SchemaUtils.listTables()
            tables.any { it.contains("GAMES", ignoreCase = true) } shouldBe true
            
            // Verify indexes exist by checking table indices
            val indices = GameTable.indices
            indices.size shouldBe 4  // 2 explicit names + 2 auto-generated hash-based names
            
            // Check that our indexes are present
            val indexNames = indices.map { it.indexName }
            
            // Verify named indexes
            val specificIndex = indices.find { it.indexName == "specificIndex" }
            specificIndex shouldNotBe null
            val uniqueIndex = indices.find { it.indexName == "uniqueGameIndex" }
            uniqueIndex shouldNotBe null
            
            // Verify auto-generated indexes (hash-based: idx_{hashId})
            // Hash IDs are deterministic based on column names
            val autoGeneratedIndices = indices.filter { it.indexName.startsWith("idx_") && it.indexName != "idx_games_title" && it.indexName != "idx_games_console_type_title" }
            autoGeneratedIndices.size shouldBe 2
            
            // Verify hash-based names are 10 characters (idx_ + 10 chars = 14 total)
            autoGeneratedIndices.forEach { index ->
                val hashPart = index.indexName.removePrefix("idx_")
                hashPart.length shouldBe 10
                hashPart.all { it.isDigit() || it in 'a'..'z' } shouldBe true
            }
            
            // Print index information for verification
            println("Found ${indices.size} indexes:")
            indices.forEach { index ->
                println("  - ${index.indexName}: ${index.createStatement().first()}")
            }
        }
    }
}
